default_platform(:android)

platform :android do
  desc "Lane for Firebase Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      upload_timeout: 600,
      app: "1:941528876299:android:025b2ec3c8116437b98e0e",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "mosmahabd952@gmail.com",
      release_notes: "first firebase distribution in my app"
    )
  end
end
