name: Android Fastlane App Distribution Workflow

on:
  push:
    branches:
      - main

jobs:
  distrubute_to_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repo code
        uses: actions/checkout@v2

      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true
          working-directory: android

      - name: Build and Distribute App
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run:
          bundle exec fastlane android firebase_distribution
        working-directory: android
  